### ISSUE TITLE
[Request] Blacklist of mobs

### ISSUE THREAD

**Issue by AntoineDehan** [SSKirillSS/cardiac#3]
Hi,

Would it be possible to add a blacklist someday where you can add mobs to not have them drop hearts?
In my pack I have some bosses with huge number of health and when they get defeaten, the spawning of all the hearts can make game crashes or slow down for a time.
Thanks.

**Comment by SSKirillSS** [comment]
Hi. Thanks for the suggestion. This feature was added in the 0.5.3 release for Minecraft 1.21.X. Now you can use regex (or just plain IDs) to override the amount of orbs that should be dropped from specific entities. This is an example of what you need to do:
```
generalPercentages:
    .*: 0.15
    minecraft:chicken: 0.0
```
As a result, all entities will drop 15% of their max health in orbs. Except chickens, since they will not drop health orbs at all.

**Comment by AntoineDehan** [comment]
Oh I'm sorry, I just updated my entire pack to 1.20.1 and mods are already porting to 1.21 damn.
Okay thanks for the answer, since I'm guessing there is no support for older versions,I'll try finding another solution.

Have a good one!

**Comment by SSKirillSS** [comment]
Well, these changes will be backported to 1.20.1 too, but It's not a main priority task. Probably 1-2 weeks.

**Comment by AntoineDehan** [comment]
Oh I understand, that's cool that it even get ported thanks a lot!

**Comment by SSKirillSS** [comment]
Just backported it
